name: template_app
description: Template app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ####---[BASE SECTION]-------------------------------------------------------------------------------

  # Architecture
  ## Presentation (https://pub.dev/packages/bloc / https://pub.dev/packages/flutter_bloc)
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # DI(Service Locator) https://pub.dev/packages/get_it
  get_it: ^7.4.1

  # Data
  ## Network
  ### https://pub.dev/packages/dio
  dio: ^5.0.2
  ### https://pub.dev/packages/retrofit
  retrofit: ^4.0.1
  ## Local Storage
  ### Hive (https://pub.dev/packages/hive / https://pub.dev/packages/hive_flutter)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ### Drift (https://pub.dev/packages/drift)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  ### Isar (https://pub.dev/packages/isar)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Utils
  ### https://pub.dev/packages/path_provider
  path_provider: ^2.1.3
  ### https://pub.dev/packages/path
  path: ^1.9.0
  ### https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.10
  ### https://pub.dev/packages/equatable
  equatable: ^2.0.5
  ### https://pub.dev/packages/permission_handler
  permission_handler: ^11.0.1
  ### https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^17.0.0
  ### https://pub.dev/packages/system_proxy
  system_proxy: ^0.1.0
  ### https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.0
  ### https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.0.3
  ### https://pub.dev/packages/image_picker
  image_picker: ^1.0.4

  # Strings anl locale
  ### https://pub.dev/packages/slang#-modifiers
  slang: ^3.25.0
  ### https://pub.dev/packages/intl
  intl: ^0.19.0
  ### https://pub.dev/packages/slang_flutter
  slang_flutter: ^3.26.0

  #UI
  ### https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.3
  ### https://pub.dev/packages/another_flushbar todo: check anr rework this!
  another_flushbar: ^1.12.30
  ### https://pub.dev/packages/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^6.0.0
  ### https://pub.dev/packages/mask_text_input_formatter
  mask_text_input_formatter: ^2.4.0
  ### https://pub.dev/packages/cached_network_image todo: check how this work!
  cached_network_image: ^3.2.2

  # Devtools
  ### https://pub.dev/packages/pretty_dio_logger logger for dio
  pretty_dio_logger: ^1.1.1
  ### https://pub.dev/packages/logger logger for console
  logger: ^2.0.2+1
  ### https://pub.dev/packages/flutter_logs logger for file
  flutter_logs: ^2.0.2+1
  ### https://pub.dev/packages/collection
  collection: ^1.17.0
  ### https://pub.dev/packages/dart_extensions
  dart_extensions: ^2.2.0
  ### https://pub.dev/packages/async
  async: ^2.11.0

  # Navigation
  auto_route: ^8.1.3

  # Json Serialization
  ### https://pub.dev/packages/json_serializable
  json_serializable: ^6.6.2
  #### https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1

  # Utils
  ### https://pub.dev/packages/share_plus
  share_plus: ^9.0.0

####---[BASE SECTION]-------------------------------------------------------------------------------
####---[IN PROJECT SECTION]-------------------------------------------------------------------------
# todo: add project needed packages here



####---[IN PROJECT SECTION]-------------------------------------------------------------------------

dev_dependencies:
  ####---[BASE SECTION]-------------------------------------------------------------------------------
  #Codegen
  ### https://pub.dev/packages/build_runner
  build_runner: ^2.4.11
  ### https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^8.0.4
  ### https://pub.dev/packages/hive_generator
  hive_generator: ^2.0.0
  ### https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^8.0.0
  ### https://pub.dev/packages/change_app_package_name
  #### how to use -> flutter pub run change_app_package_name:main com.new.package.name
  change_app_package_name: 1.1.0
  ### https://pub.dev/packages/slang
  slang_build_runner: ^3.25.0
  ### https://pub.dev/packages/drift_dev
  drift_dev: ^2.18.0
  # Lint rules todo: check this!
  flutter_lints: ^3.0.0
  chopper_generator: ^7.0.6
  isar_generator: ^3.1.0+1
####---[BASE SECTION]-------------------------------------------------------------------------------
####---[IN PROJECT SECTION]-------------------------------------------------------------------------
# todo: add project needed packages here



####---[IN PROJECT SECTION]-------------------------------------------------------------------------

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/raw/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          weight: 100
